CREATE DATABASE conference
go

USE conference
go

CREATE SCHEMA CONFERENCE

go

CREATE TABLE CONFERENCE.INSTITUICAO(

	nome		VARCHAR(15),
	endereco	VARCHAR(20)		PRIMARY KEY,
);


CREATE TABLE CONFERENCE.PESSOA(
	email		VARCHAR(20),
	nome		VARCHAR(15),
	FK_endereco	VARCHAR(20),		
	PRIMARY KEY(email), 
	FOREIGN KEY(FK_endereco)	REFERENCES CONFERENCE.INSTITUICAO(endereco), 
);


CREATE TABLE CONFERENCE.PARTICIPANTE(
	morada		VARCHAR(30),
	data_insc	DATE,
	FK_email		VARCHAR(20),
	PRIMARY KEY (FK_email),
	FOREIGN KEY (FK_email)		REFERENCES CONFERENCE.PESSOA(email),
);

CREATE TABLE CONFERENCE.ESTUDANTE(
	FK_email			VARCHAR(20),
	comprovativo	VARCHAR(30)	NOT NULL,
	PRIMARY KEY (FK_email),
	FOREIGN KEY(FK_email)		REFERENCES CONFERENCE.PESSOA(email),
);

CREATE TABLE CONFERENCE.NAO_ESTUDANTE(
	FK_email			VARCHAR(20),
	ref_trans_banc	VARCHAR(30)	NOT NULL,
	PRIMARY KEY (FK_email),
	FOREIGN KEY(FK_email)		REFERENCES CONFERENCE.PESSOA(email),
);

CREATE TABLE CONFERENCE.AUTOR(
	FK_email			VARCHAR(20),
	nome			VARCHAR(9) NOT NULL,
	PRIMARY KEY (FK_email),
	FOREIGN KEY(FK_email)		REFERENCES CONFERENCE.PESSOA(email),
);

CREATE TABLE CONFERENCE.ARTIGO(
	FK_email			VARCHAR(20),
	num_registo		INT NOT NULL,
	titulo			VARCHAR(30),
	PRIMARY KEY (num_registo),
	FOREIGN KEY(FK_email)		REFERENCES CONFERENCE.PESSOA(email),
	UNIQUE(titulo)
);